server:
  port: 8004




spring:
  application:
    name: farinfo-training



#############eureka client config#####################
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone:  http://localhost:8761/eureka/


#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri:  http://localhost:8002/oauth/token_key  #获取解析jwt，验签名key的路径
#      user-info-uri:
#    client:
#      client-id:  farinfoTraining #获取验签key需要身份认证，这里是网关的clientId
#      client-secret:  123456  #获取验签key需要身份认证，这里是网关的secret