server:
  port: 8003

spring:
  profiles:
    active: dev
  application:
    name: farinfo-benefit



#############eureka client config#####################
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone:  http://localhost:8761/eureka/
