spring:
  application:
    name: farinfo-filesys

server:
  port: 8006



#############eureka client config#####################
#eureka:
#  client:
#    #设置服务注册中心的URL
#    service-url:
#      defaultZone:  http://localhost:8761/eureka/




####################fastDFS###################
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 154.8.201.54:22122
