

spring:
  profiles:
    active: dev
  # 指定注册到eureka server上的服务名称，
  application:
    name: microsoft-benefit
  datasource:
    #url: jdbc:mysql://rm-2ze70172m6oy9qxe390130.mysql.rds.aliyuncs.com:3306/public_benefit?useSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/public_benefit?useSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root #crcdb
    password: lhy1234 #CrcDb_2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    #redis 配置
    redis:
      database: 0
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8   #最大连接数据库连接数,设 0 为没有限制
          max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
          max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 100ms
      password:
      port: 6379



#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#是否启用swagger文档
swagger2:
  enable: true




eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.195:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    ip-address: 192.168.1.100
    hostname: 192.168.1.100

#feign:
#  hystrix:
#    enabled: true



jwt:
  config:
    key: Farinfo520
    ttl: 2592000000  #

