#################################### common config : ####################################
server:
  port: 8001

spring:
  application:
    name: farinfo-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/db_oauth?useSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: lhy1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      timeout: 3000
      password:
    #    lettuce:
    #      pool:
    #        max-active: 200
    #        max-idle: 20
    #        min-idle: 5
    #        max-wait: -1

zuul:
  routes: #路由的配置是个Map，可以配置多个
    token:  #token结尾的请求，都转发到http://localhost:8002认证服务器地址
      url:  http://localhost:8002
    gongyi:  #gongyi结尾的请求，都转发到http://localhost:8003 爱心公益
      url:  http://localhost:8003
  sensitive-headers:  null  #设置敏感头设置为空，Authorization等请求头的请求，都往后转发



#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




security:
  oauth2:
    resource:
      jwt:
        key-uri:  http://localhost:8002/oauth/token_key  #获取解析jwt，验签名key的路径
    client:
      client-id:  farinfoGateway #获取验签key需要身份认证，这里是网关的clientId
      client-secret:  123456  #获取验签key需要身份认证，这里是网关的secret